### ISSUE TITLE
Please shut down your website

### ISSUE THREAD

**Issue by AGSPhoenix** [SeaRyanC/factorio-reference#6]
We are coming up on 4 years since you last updated Referencio, and there have been many changes to the game since then. An issue requesting updates for the site has been open for over 2 years.

You are certainly not required to maintain your site in exchange for all 0 income you get from it, but at this point the incorrect information just does more harm to unsuspecting players than good. If you can't spend the time to update it, please take it down, or redirect visitors to a more up to date site like [factoriocheatsheet.com](https://factoriocheatsheet.com).

**Comment by SeaRyanC** [comment]
Feel free to send a PR with the last thing listed there
